type PassportMetadataRequest = {
  wallet: string
  level: string
  xp: number
  builderScore: number
  reputation: number
  currentStreak: number
  bestStreak: number
  totalCheckIns: number
  badges: string[]
  externalUrl: string
}

type ServerRequest = {
  method?: string
  body?: Partial<PassportMetadataRequest>
}

type ServerResponse = {
  status: (code: number) => {
    json: (body: unknown) => void
  }
}

function getServerEnv(name: string) {
  const env = (globalThis as unknown as {
    process?: {
      env?: Record<string, string | undefined>
    }
  }).process?.env

  return env?.[name]
}

function isValidMetadataPayload(body: Partial<PassportMetadataRequest>) {
  return Boolean(
    body.wallet &&
      body.level &&
      typeof body.xp === "number" &&
      typeof body.builderScore === "number" &&
      typeof body.reputation === "number" &&
      typeof body.currentStreak === "number" &&
      typeof body.bestStreak === "number" &&
      typeof body.totalCheckIns === "number" &&
      Array.isArray(body.badges) &&
      body.externalUrl,
  )
}

export default async function handler(req: ServerRequest, res: ServerResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({
      error: "Method not allowed",
    })
  }

  const pinataJwt = getServerEnv("PINATA_JWT")

  if (!pinataJwt) {
    return res.status(500).json({
      error: "PINATA_JWT is not configured.",
    })
  }

  const body = req.body ?? {}

  if (!isValidMetadataPayload(body)) {
    return res.status(400).json({
      error: "Invalid passport metadata payload.",
    })
  }

  const metadata = {
    name: "Arc Builder Passport",
    description:
      "A builder identity passport generated by Arc Quest Hub using verified onchain activity, XP, reputation, streaks and check-ins.",
    external_url: body.externalUrl,
    attributes: [
      { trait_type: "Wallet", value: body.wallet },
      { trait_type: "Level", value: body.level },
      { trait_type: "XP", value: body.xp },
      { trait_type: "Builder Score", value: body.builderScore },
      { trait_type: "Reputation", value: body.reputation },
      { trait_type: "Current Streak", value: body.currentStreak },
      { trait_type: "Best Streak", value: body.bestStreak },
      { trait_type: "Check-ins", value: body.totalCheckIns },
      {
        trait_type: "Badges",
        value: body.badges && body.badges.length > 0 ? body.badges.join(", ") : "None",
      },
    ],
  }

  try {
    const pinataResponse = await fetch(
      "https://api.pinata.cloud/pinning/pinJSONToIPFS",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${pinataJwt}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          pinataMetadata: {
            name: `arc-builder-passport-${body.wallet}`,
          },
          pinataContent: metadata,
        }),
      },
    )

    if (!pinataResponse.ok) {
      return res.status(502).json({
        error: "Failed to upload metadata to IPFS.",
      })
    }

    const result = (await pinataResponse.json()) as {
      IpfsHash?: string
    }

    if (!result.IpfsHash) {
      return res.status(502).json({
        error: "IPFS upload did not return a CID.",
      })
    }

    return res.status(200).json({
      cid: result.IpfsHash,
      tokenUri: `ipfs://${result.IpfsHash}`,
      gatewayUrl: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}`,
    })
  } catch {
    return res.status(500).json({
      error: "Unexpected metadata upload error.",
    })
  }
}