type PassportMetadataRequest = {
  wallet: string
  level: string
  xp: number
  builderScore: number
  reputation: number
  currentStreak: number
  bestStreak: number
  totalCheckIns: number
  badges: string[]
  externalUrl: string
}

type ServerRequest = {
  method?: string
  body?: Partial<PassportMetadataRequest>
}

type ServerResponse = {
  status: (code: number) => {
    json: (body: unknown) => void
  }
}

function getServerEnv(name: string) {
  const env = (globalThis as unknown as {
    process?: {
      env?: Record<string, string | undefined>
    }
  }).process?.env

  return env?.[name]
}

function isValidMetadataPayload(body: Partial<PassportMetadataRequest>) {
  return Boolean(
    body.wallet &&
      body.level &&
      typeof body.xp === "number" &&
      typeof body.builderScore === "number" &&
      typeof body.reputation === "number" &&
      typeof body.currentStreak === "number" &&
      typeof body.bestStreak === "number" &&
      typeof body.totalCheckIns === "number" &&
      Array.isArray(body.badges) &&
      body.externalUrl,
  )
}

function escapeSvg(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
}

function createPassportSvg(body: PassportMetadataRequest) {
  const wallet = escapeSvg(body.wallet)
  const level = escapeSvg(body.level)
  const badges = body.badges.length > 0 ? body.badges.join(" • ") : "No badges yet"

  return `
<svg width="1200" height="675" viewBox="0 0 1200 675" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="675" fill="#020617"/>
  <rect x="40" y="40" width="1120" height="595" rx="36" fill="#0f172a" stroke="#67e8f9" stroke-width="2"/>
  <circle cx="1020" cy="145" r="95" fill="#581c87" opacity="0.55"/>
  <circle cx="170" cy="540" r="120" fill="#0891b2" opacity="0.28"/>
  <text x="80" y="105" fill="#67e8f9" font-family="Arial" font-size="26" font-weight="700" letter-spacing="4">ARC BUILDER PASSPORT</text>
  <text x="80" y="170" fill="white" font-family="Arial" font-size="48" font-weight="900">${level}</text>
  <text x="80" y="220" fill="#94a3b8" font-family="Arial" font-size="22">${wallet}</text>

  <rect x="80" y="285" width="300" height="110" rx="22" fill="#111827" stroke="#334155"/>
  <text x="110" y="330" fill="#94a3b8" font-family="Arial" font-size="20">XP</text>
  <text x="110" y="375" fill="#c084fc" font-family="Arial" font-size="44" font-weight="900">${body.xp}</text>

  <rect x="450" y="285" width="300" height="110" rx="22" fill="#111827" stroke="#334155"/>
  <text x="480" y="330" fill="#94a3b8" font-family="Arial" font-size="20">Builder Score</text>
  <text x="480" y="375" fill="#67e8f9" font-family="Arial" font-size="44" font-weight="900">${body.builderScore}</text>

  <rect x="820" y="285" width="300" height="110" rx="22" fill="#111827" stroke="#334155"/>
  <text x="850" y="330" fill="#94a3b8" font-family="Arial" font-size="20">Reputation</text>
  <text x="850" y="375" fill="#34d399" font-family="Arial" font-size="44" font-weight="900">${body.reputation}/100</text>

  <rect x="80" y="440" width="300" height="90" rx="22" fill="#111827" stroke="#334155"/>
  <text x="110" y="475" fill="#94a3b8" font-family="Arial" font-size="18">Current Streak</text>
  <text x="110" y="515" fill="#fb923c" font-family="Arial" font-size="34" font-weight="900">${body.currentStreak}</text>

  <rect x="450" y="440" width="300" height="90" rx="22" fill="#111827" stroke="#334155"/>
  <text x="480" y="475" fill="#94a3b8" font-family="Arial" font-size="18">Best Streak</text>
  <text x="480" y="515" fill="#facc15" font-family="Arial" font-size="34" font-weight="900">${body.bestStreak}</text>

  <rect x="820" y="440" width="300" height="90" rx="22" fill="#111827" stroke="#334155"/>
  <text x="850" y="475" fill="#94a3b8" font-family="Arial" font-size="18">Check-ins</text>
  <text x="850" y="515" fill="#67e8f9" font-family="Arial" font-size="34" font-weight="900">${body.totalCheckIns}</text>

  <text x="80" y="590" fill="#e2e8f0" font-family="Arial" font-size="22" font-weight="700">${escapeSvg(badges)}</text>
  <text x="80" y="620" fill="#64748b" font-family="Arial" font-size="16">Generated by Arc Quest Hub</text>
</svg>`
}

export default async function handler(req: ServerRequest, res: ServerResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" })
  }

  const pinataJwt = getServerEnv("PINATA_JWT")

  if (!pinataJwt) {
    return res.status(500).json({ error: "PINATA_JWT is not configured." })
  }

  const body = req.body ?? {}

  if (!isValidMetadataPayload(body)) {
    return res.status(400).json({ error: "Invalid passport metadata payload." })
  }

  const typedBody = body as PassportMetadataRequest
  const svg = createPassportSvg(typedBody)
  const imageData = `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`

  const metadata = {
    name: "Arc Builder Passport",
    description:
      "A builder identity passport generated by Arc Quest Hub using verified onchain activity, XP, reputation, streaks and check-ins.",
    external_url: typedBody.externalUrl,
    image: imageData,
    image_data: svg,
    attributes: [
      { trait_type: "Wallet", value: typedBody.wallet },
      { trait_type: "Level", value: typedBody.level },
      { trait_type: "XP", value: typedBody.xp },
      { trait_type: "Builder Score", value: typedBody.builderScore },
      { trait_type: "Reputation", value: typedBody.reputation },
      { trait_type: "Current Streak", value: typedBody.currentStreak },
      { trait_type: "Best Streak", value: typedBody.bestStreak },
      { trait_type: "Check-ins", value: typedBody.totalCheckIns },
      {
        trait_type: "Badges",
        value: typedBody.badges.length > 0 ? typedBody.badges.join(", ") : "None",
      },
    ],
  }

  try {
    const pinataResponse = await fetch(
      "https://api.pinata.cloud/pinning/pinJSONToIPFS",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${pinataJwt}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          pinataMetadata: {
            name: `arc-builder-passport-${typedBody.wallet}`,
          },
          pinataContent: metadata,
        }),
      },
    )

    if (!pinataResponse.ok) {
      return res.status(502).json({ error: "Failed to upload metadata to IPFS." })
    }

    const result = (await pinataResponse.json()) as { IpfsHash?: string }

    if (!result.IpfsHash) {
      return res.status(502).json({ error: "IPFS upload did not return a CID." })
    }

    return res.status(200).json({
      cid: result.IpfsHash,
      tokenUri: `ipfs://${result.IpfsHash}`,
      gatewayUrl: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}`,
    })
  } catch {
    return res.status(500).json({ error: "Unexpected metadata upload error." })
  }
}